### ISSUE TITLE
Ability to customise icon colour

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#39]
I'm thinking of adding some setting where you would have a colour picker to choose icon colour.
There will also be some setting to keep the icon colour untouched.

**Comment by Sir-Martin-Esq-III** [comment]
Hey, I was thinking about picking this up but the requirements don't seem as fleshed out as I'd like so I have a few questions. 

- Where would this fit within the UI? On the context menu when you right-click? On the file info section on the side(I would guess the former rather than latter...)? 

>There will also be some setting to keep the icon colour untouched. 

- Wouldn't this just be the default and not an explicit setting (unless you meant to reset to the original colour)

- Are there any other requirements that might have been missed out?

**Comment by Sandyacvedo** [comment]
hey i would like to work on this, but one question this is feature is going to be only available for svg icons ?
